CREATE TABLE IF NOT EXISTS agents (
    agent_id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    mobile VARCHAR(30) NOT NULL,
    email VARCHAR(150) DEFAULT NULL,
    address TEXT,
    city VARCHAR(100) DEFAULT NULL,
    state VARCHAR(100) DEFAULT NULL,
    pincode VARCHAR(20) DEFAULT NULL,
    joining_date DATE DEFAULT NULL,
    status ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
    notes TEXT,
    account_holder_name VARCHAR(150) DEFAULT NULL,
    bank_name VARCHAR(150) DEFAULT NULL,
    account_number VARCHAR(80) DEFAULT NULL,
    ifsc_code VARCHAR(30) DEFAULT NULL,
    branch_name VARCHAR(150) DEFAULT NULL,
    upi_id VARCHAR(120) DEFAULT NULL,
    password_hash VARCHAR(255) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL,
    INDEX idx_agents_status (status),
    INDEX idx_agents_mobile (mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agent_plan_assignments (
    assignment_id INT AUTO_INCREMENT PRIMARY KEY,
    agent_id INT NOT NULL,
    plan_id INT NOT NULL,
    commission_percentage DECIMAL(7,2) NOT NULL DEFAULT 0.00,
    status ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL,
    UNIQUE KEY uq_agent_plan (agent_id, plan_id),
    INDEX idx_agent_plan_agent (agent_id),
    INDEX idx_agent_plan_plan (plan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agent_sales (
    sale_id INT AUTO_INCREMENT PRIMARY KEY,
    sale_reference VARCHAR(80) NOT NULL,
    customer_matri_id VARCHAR(80) DEFAULT NULL,
    customer_name VARCHAR(150) NOT NULL,
    customer_mobile VARCHAR(40) DEFAULT NULL,
    customer_email VARCHAR(150) DEFAULT NULL,
    agent_id INT NOT NULL,
    agent_customer_id INT DEFAULT NULL,
    plan_id INT DEFAULT NULL,
    plan_name VARCHAR(150) NOT NULL,
    plan_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    payment_status ENUM('Pending','Clear','Failed','Refunded') NOT NULL DEFAULT 'Clear',
    sale_status ENUM('Pending','Confirmed','Cancelled') NOT NULL DEFAULT 'Confirmed',
    commission_source VARCHAR(80) NOT NULL DEFAULT 'Manual Customer Purchase',
    payment_reference_id VARCHAR(120) DEFAULT NULL,
    sale_date DATE NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_agent_sale_reference (sale_reference),
    INDEX idx_agent_sales_agent (agent_id),
    INDEX idx_agent_sales_customer (agent_customer_id),
    INDEX idx_agent_sales_plan (plan_id),
    INDEX idx_agent_sales_payment_ref (payment_reference_id),
    INDEX idx_agent_sales_date (sale_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agent_commissions (
    commission_id INT AUTO_INCREMENT PRIMARY KEY,
    sale_id INT NOT NULL,
    agent_id INT NOT NULL,
    plan_id INT DEFAULT NULL,
    sale_date DATE NOT NULL,
    commission_percentage DECIMAL(7,2) NOT NULL DEFAULT 0.00,
    commission_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    commission_source VARCHAR(80) NOT NULL DEFAULT 'Manual Customer Purchase',
    payment_reference_id VARCHAR(120) DEFAULT NULL,
    commission_status ENUM('Pending','On Hold','Eligible','Withdrawal Requested','Approved','Paid','Rejected') NOT NULL DEFAULT 'On Hold',
    eligible_date DATE NOT NULL,
    payment_date DATE DEFAULT NULL,
    admin_remarks TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL,
    UNIQUE KEY uq_agent_commission_sale (sale_id),
    INDEX idx_agent_comm_agent (agent_id),
    INDEX idx_agent_comm_status (commission_status),
    INDEX idx_agent_comm_eligible (eligible_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agent_withdrawal_requests (
    withdrawal_id INT AUTO_INCREMENT PRIMARY KEY,
    agent_id INT NOT NULL,
    requested_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    available_balance DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    request_date DATE NOT NULL,
    status ENUM('Pending','Approved','Rejected','Paid') NOT NULL DEFAULT 'Pending',
    admin_remarks TEXT,
    payment_date DATE DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL,
    INDEX idx_agent_with_agent (agent_id),
    INDEX idx_agent_with_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agent_customers (
    customer_id INT AUTO_INCREMENT PRIMARY KEY,
    registered_user_id INT DEFAULT NULL,
    registered_matri_id VARCHAR(80) DEFAULT NULL,
    agent_id INT NOT NULL,
    customer_name VARCHAR(150) NOT NULL,
    customer_mobile VARCHAR(40) NOT NULL,
    customer_email VARCHAR(150) DEFAULT NULL,
    plan_id INT DEFAULT NULL,
    plan_name VARCHAR(150) DEFAULT NULL,
    customer_status ENUM('Interested','Follow Up','Purchased','Not Interested') NOT NULL DEFAULT 'Interested',
    notes TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL,
    linked_at DATETIME DEFAULT NULL,
    INDEX idx_agent_customer_agent (agent_id),
    INDEX idx_agent_customer_plan (plan_id),
    INDEX idx_agent_customer_mobile (customer_mobile),
    INDEX idx_agent_customer_email (customer_email),
    INDEX idx_agent_customer_registered_user (registered_user_id),
    INDEX idx_agent_customer_registered_matri (registered_matri_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
